# Generated by Django 6.0.1 on 2026-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_image1_product_image2_product_image3_and_more'),
        ('user', '0003_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='liked',
            field=models.ManyToManyField(related_name='product', to='user.profilemodel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='product_images'),
        ),
    ]
