# Generated by Django 6.0.1 on 2026-02-15 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_liked_alter_product_main_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='liked',
            new_name='wishlist',
        ),
    ]
