# Generated by Django 6.0.1 on 2026-02-15 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_wishlist'),
        ('user', '0003_alter_profilemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(related_name='wish_list', to='user.profilemodel'),
        ),
    ]
