# Generated by Django 6.0.1 on 2026-01-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute', '0002_rename_curses_curse_rename_professors_professor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curse',
            old_name='star_date',
            new_name='start_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='curse',
        ),
        migrations.AddField(
            model_name='student',
            name='curse',
            field=models.ManyToManyField(to='institute.curse'),
        ),
    ]
